/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BuyerIndexRouteImport } from './routes/buyer/index'
import { Route as SellerUploadRouteImport } from './routes/seller/upload'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as SellerOnboardingRouteImport } from './routes/seller/onboarding'
import { Route as SellerListingsRouteImport } from './routes/seller/listings'
import { Route as SellerDriversRouteImport } from './routes/seller/drivers'
import { Route as SellerDispatchesRouteImport } from './routes/seller/dispatches'
import { Route as ListingIdRouteImport } from './routes/listing/$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as BuyerTrackingRouteImport } from './routes/buyer/tracking'
import { Route as BuyerProfileRouteImport } from './routes/buyer/profile'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRoute,
} as any)
const SellerUploadRoute = SellerUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SellerRoute,
} as any)
const SellerListingsRoute = SellerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDriversRoute = SellerDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDispatchesRoute = SellerDispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => SellerRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerTrackingRoute = BuyerTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerProfileRoute = BuyerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BuyerRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/tracking': typeof BuyerTrackingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/seller/dispatches': typeof SellerDispatchesRoute
  '/seller/drivers': typeof SellerDriversRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/upload': typeof SellerUploadRoute
  '/buyer/': typeof BuyerIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/tracking': typeof BuyerTrackingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/seller/dispatches': typeof SellerDispatchesRoute
  '/seller/drivers': typeof SellerDriversRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/upload': typeof SellerUploadRoute
  '/buyer': typeof BuyerIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/tracking': typeof BuyerTrackingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/seller/dispatches': typeof SellerDispatchesRoute
  '/seller/drivers': typeof SellerDriversRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/upload': typeof SellerUploadRoute
  '/buyer/': typeof BuyerIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/buyer'
    | '/marketplace'
    | '/sell'
    | '/seller'
    | '/auth/login'
    | '/auth/signup'
    | '/buyer/profile'
    | '/buyer/tracking'
    | '/categories/$slug'
    | '/listing/$id'
    | '/seller/dispatches'
    | '/seller/drivers'
    | '/seller/listings'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/upload'
    | '/buyer/'
    | '/categories/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/marketplace'
    | '/sell'
    | '/auth/login'
    | '/auth/signup'
    | '/buyer/profile'
    | '/buyer/tracking'
    | '/categories/$slug'
    | '/listing/$id'
    | '/seller/dispatches'
    | '/seller/drivers'
    | '/seller/listings'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/upload'
    | '/buyer'
    | '/categories'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/buyer'
    | '/marketplace'
    | '/sell'
    | '/seller'
    | '/auth/login'
    | '/auth/signup'
    | '/buyer/profile'
    | '/buyer/tracking'
    | '/categories/$slug'
    | '/listing/$id'
    | '/seller/dispatches'
    | '/seller/drivers'
    | '/seller/listings'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/upload'
    | '/buyer/'
    | '/categories/'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ListingIdRoute: typeof ListingIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/seller/upload': {
      id: '/seller/upload'
      path: '/upload'
      fullPath: '/seller/upload'
      preLoaderRoute: typeof SellerUploadRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/listings': {
      id: '/seller/listings'
      path: '/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof SellerListingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/drivers': {
      id: '/seller/drivers'
      path: '/drivers'
      fullPath: '/seller/drivers'
      preLoaderRoute: typeof SellerDriversRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/dispatches': {
      id: '/seller/dispatches'
      path: '/dispatches'
      fullPath: '/seller/dispatches'
      preLoaderRoute: typeof SellerDispatchesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/tracking': {
      id: '/buyer/tracking'
      path: '/tracking'
      fullPath: '/buyer/tracking'
      preLoaderRoute: typeof BuyerTrackingRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/profile': {
      id: '/buyer/profile'
      path: '/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof BuyerProfileRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuyerRouteChildren {
  BuyerProfileRoute: typeof BuyerProfileRoute
  BuyerTrackingRoute: typeof BuyerTrackingRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerProfileRoute: BuyerProfileRoute,
  BuyerTrackingRoute: BuyerTrackingRoute,
  BuyerIndexRoute: BuyerIndexRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface SellerRouteChildren {
  SellerDispatchesRoute: typeof SellerDispatchesRoute
  SellerDriversRoute: typeof SellerDriversRoute
  SellerListingsRoute: typeof SellerListingsRoute
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerUploadRoute: typeof SellerUploadRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerDispatchesRoute: SellerDispatchesRoute,
  SellerDriversRoute: SellerDriversRoute,
  SellerListingsRoute: SellerListingsRoute,
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerUploadRoute: SellerUploadRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BuyerRoute: BuyerRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ListingIdRoute: ListingIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
